# Generated by Django 5.1 on 2024-10-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0012_rename_disrict_coordinatepoint_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coordinatepoint',
            old_name='disrict',
            new_name='district',
        ),
    ]
