# Generated by Django 5.1 on 2024-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0013_rename_disrict_coordinatepoint_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='estimated_time',
            field=models.IntegerField(default=0),
        ),
    ]
