# Generated by Django 5.1 on 2024-10-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0014_alter_route_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='pickup_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.coordinatepoint'),
        ),
    ]
