# Generated by Django 5.1 on 2024-10-15 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0015_alter_passenger_pickup_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='passenger',
            name='pickup_address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.coordinatepoint'),
        ),
    ]
