# Generated by Django 5.1 on 2024-10-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0016_remove_passenger_pickup_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='pickup_address_id',
            new_name='pickup_address',
        ),
    ]
