# Generated by Django 5.1 on 2024-10-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0017_rename_pickup_address_id_passenger_pickup_address'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatepoint',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
