# Generated by Django 5.1 on 2024-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0019_remove_passenger_pickup_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='pickup_addresses',
            field=models.ManyToManyField(blank=True, related_name='pickup_points', to='TransLogix_djangoProject.coordinatepoint'),
        ),
    ]
