# Generated by Django 5.1 on 2024-10-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0020_alter_passenger_pickup_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatepoint',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='owner_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
