# Generated by Django 5.1 on 2024-10-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0022_group_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
