# Generated by Django 5.1 on 2024-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0023_passenger_is_active_passenger_is_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatepoint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
