# Generated by Django 5.1 on 2024-11-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0025_remove_coordinatepoint_house_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatepoint',
            name='house',
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
