# Generated by Django 5.1 on 2024-11-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0026_remove_coordinatepoint_house_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatepoint',
            name='house_number',
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.house'),
        ),
    ]
