# Generated by Django 5.1 on 2024-12-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0027_remove_coordinatepoint_house_number_and_more'),
    ]

    operations = [


        migrations.AddField(
            model_name='driver',
            name='citizenship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='contract_type',
            field=models.CharField(default='default contract', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='first_name', max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issue_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issuer',
            field=models.CharField(blank=True, default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='related_vehicles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='residence_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='last_name', max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(db_column='driver_id', on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.driver'),
        ),
    ]
