# Generated by Django 5.1 on 2024-12-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0028_remove_driver_name_remove_driver_user_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='city_fuel_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_volume',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='highway_fuel_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_to',
            field=models.CharField(default='Not specified', max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Petrol', max_length=50),
        ),
    ]
