# Generated by Django 5.1 on 2024-12-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0029_remove_driver_name_remove_driver_related_vehicles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='related_vehicles',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle',
        ),
    ]
