# Generated by Django 5.1 on 2024-12-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0030_remove_driver_name_remove_driver_related_vehicles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
