# Generated by Django 5.1 on 2024-12-27 13:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0034_driver_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
            },
        ),
        migrations.CreateModel(
            name='DriverVehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(default=django.utils.timezone.now)),
                ('order_number', models.CharField(max_length=50)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='TransLogix_djangoProject.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='TransLogix_djangoProject.vehicle')),
            ],
            options={
                'verbose_name': 'Driver Vehicle Assignment',
                'verbose_name_plural': 'Driver Vehicle Assignments',
            },
        ),
    ]
