# Generated by Django 5.0.2 on 2025-01-09 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0037_alter_vehicle_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('coordinate_point', models.ForeignKey(db_column='coordinate_point_id', on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='TransLogix_djangoProject.coordinatepoint')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_points', to='TransLogix_djangoProject.passenger')),
                ('route', models.ForeignKey(db_column='route_id', on_delete=django.db.models.deletion.CASCADE, related_name='route_points', to='TransLogix_djangoProject.route')),
            ],
            options={
                'verbose_name': 'Route Point',
                'verbose_name_plural': 'Route Points',
                'ordering': ['route', 'sequence_number'],
            },
        ),
    ]
