# Generated by Django 5.0.2 on 2025-01-09 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0038_alter_route_route_id_routepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_destination', to='TransLogix_djangoProject.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_point',
            field=models.ForeignKey(db_column='end_point_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_end', to='TransLogix_djangoProject.coordinatepoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(db_column='origin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_origin', to='TransLogix_djangoProject.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_point',
            field=models.ForeignKey(db_column='start_point_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_start', to='TransLogix_djangoProject.coordinatepoint'),
        ),
    ]
