# Generated by Django 5.0.2 on 2025-01-09 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0039_alter_route_destination_alter_route_end_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerTripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint_type', models.CharField(choices=[('pickup', 'Посадка'), ('dropoff', 'Висадка'), ('work', 'Робота')], max_length=50)),
                ('planned_datetime', models.DateTimeField()),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direction', models.CharField(choices=[('to_work', 'На роботу'), ('to_home', 'Додому')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('dropoff_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_trip_requests', to='TransLogix_djangoProject.coordinatepoint')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='TransLogix_djangoProject.passenger')),
                ('pickup_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_trip_requests', to='TransLogix_djangoProject.coordinatepoint')),
            ],
            options={
                'verbose_name': 'Passenger Trip Request',
                'verbose_name_plural': 'Passenger Trip Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
