# Generated by Django 5.0.2 on 2025-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0040_passengertriprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertriprequest',
            name='planned_datetime',
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
