# Generated by Django 5.0.2 on 2025-01-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0041_remove_passengertriprequest_planned_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertriprequest',
            name='direction',
            field=models.CharField(choices=[('to_work', 'На роботу'), ('to_home', 'Додому')], max_length=20),
        ),
    ]
