# Generated by Django 5.0.2 on 2025-01-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0042_alter_passengertriprequest_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengertriprequest',
            name='direction',
            field=models.CharField(choices=[('HOME_TO_WORK', 'Home to Work'), ('WORK_TO_HOME', 'Work to Home')], default='HOME_TO_WORK', max_length=20),
        ),
    ]
