# Generated by Django 5.0.2 on 2025-01-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0043_alter_passengertriprequest_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengertriprequest',
            name='endpoint_type',
        ),
    ]
