# Generated by Django 5.0.2 on 2025-01-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0045_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='allow_multiple_work_addresses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_passengers',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_route_distance',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='max_stops',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='min_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
