# Generated by Django 5.0.2 on 2025-01-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0046_usersettings_allow_multiple_work_addresses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPassengerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_city', models.CharField(max_length=255)),
                ('start_street', models.CharField(max_length=255)),
                ('start_building', models.CharField(max_length=50)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('start_passenger_name', models.CharField(max_length=255)),
                ('start_passenger_id', models.IntegerField(blank=True, help_text='ID першого пасажира', null=True)),
                ('start_address_type', models.CharField(choices=[('work', 'Робоча'), ('pickup', 'Посадка'), ('dropoff', 'Висадка')], max_length=20)),
                ('start_coordinate_id', models.IntegerField(blank=True, help_text='ID першої точки координат', null=True)),
                ('start_request_id', models.IntegerField(blank=True, help_text='ID першої заявки', null=True)),
                ('end_city', models.CharField(max_length=255)),
                ('end_street', models.CharField(max_length=255)),
                ('end_building', models.CharField(max_length=50)),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('end_passenger_name', models.CharField(max_length=255)),
                ('end_passenger_id', models.IntegerField(blank=True, help_text='ID останнього пасажира', null=True)),
                ('end_address_type', models.CharField(choices=[('work', 'Робоча'), ('pickup', 'Посадка'), ('dropoff', 'Висадка')], max_length=20)),
                ('end_coordinate_id', models.IntegerField(blank=True, help_text='ID останньої точки координат', null=True)),
                ('end_request_id', models.IntegerField(blank=True, help_text='ID останньої заявки', null=True)),
                ('direction', models.CharField(choices=[('HOME_TO_WORK', 'З дому на роботу'), ('WORK_TO_HOME', 'З роботи додому')], max_length=20)),
                ('estimated_start_time', models.DateTimeField()),
                ('estimated_end_time', models.DateTimeField()),
                ('estimated_travel_time', models.PositiveIntegerField(help_text='Час у дорозі (хвилини)')),
                ('estimated_wait_time', models.PositiveIntegerField(help_text='Час очікування (хвилини)')),
                ('has_both_directions', models.BooleanField(default=False)),
                ('route_distance_km', models.FloatField(help_text='Дистанція маршруту (км)')),
                ('stop_count', models.PositiveIntegerField()),
                ('passenger_count', models.PositiveIntegerField()),
                ('multiple_work_addresses_allowed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Активний (так/ні)')),
                ('allow_copy', models.BooleanField(default=True, help_text='Дозволено копіювати (так/ні)')),
                ('allow_edit', models.BooleanField(default=True, help_text='Дозволено редагувати (так/ні)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Час створення')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Час редагування')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Час деактивації', null=True)),
                ('assigned_route_id', models.ForeignKey(blank=True, help_text='Призначений для маршрута (ID маршруту або null)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.route')),
            ],
        ),
    ]
