# Generated by Django 5.0.2 on 2025-01-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0047_orderedpassengerlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedpassengerlist',
            old_name='end_passenger_name',
            new_name='end_passenger_first_name',
        ),
        migrations.RenameField(
            model_name='orderedpassengerlist',
            old_name='start_passenger_name',
            new_name='end_passenger_last_name',
        ),
        migrations.AddField(
            model_name='orderedpassengerlist',
            name='start_passenger_first_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedpassengerlist',
            name='start_passenger_last_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
