# Generated by Django 5.0.2 on 2025-01-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('TransLogix_djangoProject', '0048_rename_end_passenger_name_orderedpassengerlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passengertriprequest',
            options={'ordering': ['ordered_list', 'sequence_number'], 'verbose_name': 'Passenger Trip Request', 'verbose_name_plural': 'Passenger Trip Requests'},
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='dropoff_time_in_route',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='included_in_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='included_in_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='included_in_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='ordered_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_requests', to='TransLogix_djangoProject.orderedpassengerlist'),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='pickup_time_in_route',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='travel_time_in_route',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passengertriprequest',
            name='wait_time_at_work',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
