# Generated by Django 5.1.6 on 2025-03-03 19:48

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0049_alter_passengertriprequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryPassengerList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('filter_params', models.JSONField()),
                ('passengers', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2025, 3, 4, 19, 48, 25, 39305, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
