# Generated by Django 5.1.6 on 2025-03-03 22:14

import TransLogix_djangoProject.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0050_temporarypassengerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarypassengerlist',
            name='passengers',
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='direction',
            field=models.CharField(blank=True, choices=[('HOME_TO_WORK', 'На роботу'), ('WORK_TO_HOME', 'Додому')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='estimated_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='estimated_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='estimated_travel_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='estimated_wait_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='passenger_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='requests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='route_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarypassengerlist',
            name='stop_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporarypassengerlist',
            name='expires_at',
            field=models.DateTimeField(default=TransLogix_djangoProject.models.default_expires_at),
        ),
        migrations.AlterField(
            model_name='temporarypassengerlist',
            name='filter_params',
            field=models.JSONField(default=dict),
        ),
    ]
