# Generated by Django 5.1.6 on 2025-03-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0051_remove_temporarypassengerlist_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarypassengerlist',
            name='session_id',
            field=models.CharField(max_length=36),
        ),
    ]
