# Generated by Django 4.2.20 on 2025-04-30 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0052_alter_temporarypassengerlist_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePlanDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('route_date', models.DateField()),
                ('total_distance_km', models.FloatField(default=0.0)),
                ('total_duration_min', models.FloatField(default=0.0)),
                ('total_fuel_liters', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteDraftList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_index', models.IntegerField()),
                ('data_json', models.JSONField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('duration_min', models.FloatField(default=0.0)),
                ('fuel_liters', models.FloatField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_lists', to='TransLogix_djangoProject.routeplandraft')),
            ],
        ),
    ]
