# Generated by Django 4.2.20 on 2025-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0053_routeplandraft_routedraftlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='save',
            field=models.BooleanField(default=False, help_text='automatically save route plan after optimization'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='strategy',
            field=models.CharField(default='min_distance', help_text='optimization strategy: min_distance, min_duration, balanced, auto_vehicle_limit, min_fuel_cost', max_length=50),
        ),
    ]
