# Generated by Django 4.2.20 on 2025-05-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0054_usersettings_save_usersettings_strategy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='save',
            new_name='auto_save',
        ),
    ]
