# Generated by Django 5.1 on 2024-09-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0004_alter_user_options_alter_user_managers_route_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
