# Generated by Django 5.1 on 2024-10-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0011_remove_user_role_alter_user_id_alter_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
