# Generated by Django 5.1 on 2024-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0012_alter_route_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
