# Generated by Django 5.1 on 2024-10-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0014_remove_bookingrequest_route_remove_trip_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(default='Unknown', max_length=100)),
                ('destination', models.CharField(default='Unknown', max_length=100)),
                ('start_location', models.CharField(default='Unknown', max_length=200)),
                ('end_location', models.CharField(default='Unknown', max_length=200)),
                ('date', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estimated_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
