# Generated by Django 5.1 on 2024-10-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0015_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
