# Generated by Django 5.1 on 2024-10-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0016_route_route_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('department', models.CharField(max_length=100, verbose_name='Департамент')),
                ('pickup_address', models.CharField(max_length=200, verbose_name='Адреса точки посадки')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна адреса')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
