# Generated by Django 5.1 on 2024-10-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from TransLogix_djangoProject.models import Passenger, Route, CoordinatePoint


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0017_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),

        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination', 'date')},
        ),
        migrations.CreateModel(
            name='CoordinatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('pickup', 'Pickup Location'), ('dropoff', 'Dropoff Location'), ('departure', 'Bus Departure'), ('arrival', 'Bus Arrival'), ('parking', 'Night Parking'), ('refuel', 'Refuel'), ('repair', 'Repair'), ('manual_address', 'Manual Address'), ('user_created', 'User Created')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.city')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.country')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_end', to='TransLogix_djangoProject.coordinatepoint'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_start', to='TransLogix_djangoProject.coordinatepoint'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.country')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.region'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.region'),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.city')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatepoint',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TransLogix_djangoProject.street'),
        ),
    ]

