# Generated by Django 5.1 on 2024-10-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0019_vehicle_status_passengerroute'),
    ]

    operations = [

        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=20)),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransLogix_djangoProject.street')),
            ],
        ),
    ]
