# Generated by Django 5.1 on 2024-10-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransLogix_djangoProject', '0020_vehicle_status_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_location',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_destination', to='TransLogix_djangoProject.city'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_origin', to='TransLogix_djangoProject.city'),
        ),
    ]
